on custom redis message:
	if redis channel = {-config::rtp::redis::channel::random-teleport}:

		encode redis message as json to {_json::*}

		set {_server} to {_json::server::target}
		if {_server} != get_hostname():
			stop

		set {_uuid} to {_json::message::uuid}
		set {_p} to ({_uuid} parsed as offlineplayer)
		set {_environment} to {_json::message::environment}

		random_teleport({_p}, {_environment})