# A {_weight} ami meghatározza, hogy hol helyezkedjen el a tablistán
# minél több     (pl.: "a-admin")   annál feljebb
# minél kevesebb (pl.: "z-default") annál lejjebb
# A -> Z
function edit_weight(rank: text, weight: text):

	set {_document} to get_document({-config::rank::collection::rank}, "rank", {_rank})
	if {_document} is set:

		set mongo value "weight" of {_document} to {_weight}
		update mongo document {_document} into get_collection({-config::rank::collection::rank})