on load:

    set {-config::redis::list::commandspy} to "server:commandspy"
    set {-config::redis::channel::global-message} to "server:global-message"
    set {-config::redis::channel::player-message} to "server:player-message"
    set {-config::redis::channel::teleport-player} to "server:teleport:player:%get_hostname()%"
    set {-config::redis::channel::teleport-location} to "server:teleport:location:%get_hostname()%"
    set {-config::redis::channel::loaded-islands} to "server:island:loaded-islands:" 
    set {-config::redis::channel::online-players} to "server:online-players:"
    set {-config::redis::channel::server-list} to "server:server-list"