function accept_invite(p: player):

	if (metadata "island_invite" of {_p}) is not set:
		stop
	set {_ID} to (metadata "island_invite" of {_p})

	if get_player_island_id({_p}) is set:
		stop

	if get_island_members({_ID}) contains {_p}:
		stop

	delete (metadata "island_invite" of {_p})

	add_island_member({_p}, {_ID})
	send feedback("success", "%{_p}% csatlakozott a szigethez") to get_island_members({_ID})