function get_upgrade_money(material: text, level: integer) :: number:

	set {_content} to get_item_yaml_config({_material}, {_level})
	encode {_content} as yaml to {_yaml::*}

	loop indices of {_yaml::req::*}:
		set {_type} to {_yaml::req::%loop-value%::type} 
		
		if {_type} != "money":
			continue

		set {_amount} to {_yaml::req::%loop-value%::amount}
		add {_amount} to {_money}
	
	return {_money}