function get_upgrade_items(material: text, level: integer) :: items:

	set {_content} to get_item_yaml_config({_material}, {_level})
	encode {_content} as yaml to {_yaml::*}

	loop indices of {_yaml::req::*}:
		set {_type} to {_yaml::req::%loop-value%::type} 
		
		if {_type} != "material":
			continue

		set {_item} to ({_yaml::req::%loop-value%::item} parsed as item)
		set {_amount} to {_yaml::req::%loop-value%::amount}

		add {_amount} of {_item} to {_items::*}

	return {_items::*}