function get_upgrade_experience(material: text, level: integer) :: integer:

	set {_content} to get_item_yaml_config({_material}, {_level})
	encode {_content} as yaml to {_yaml::*}
	
	loop indices of {_yaml::req::*}:
		set {_type} to {_yaml::req::%loop-value%::type} 
		
		if {_type} != "experience":
			continue

		set {_amount} to {_yaml::req::%loop-value%::amount}
		add {_amount} to {_experience}
	
	return {_experience}