command /spawn:
	executable by: players
	usage: &f/spawn
	description: Elteleportálás a spawnra
	trigger:
		spawn(player)

function spawn(p: player):

	set {_loc} to spawn of world("Spawn")

	set {_randomX} to a random number between -3 and 3
	set {_randomZ} to a random number between -3 and 3

	add {_randomX} to x-coordinate of {_loc}
	add {_randomZ} to z-coordinate of {_loc}

	teleport {_p} to {_loc}