command /tpadeny:

	prefix: kockacraft
	executable by: players
	usage: &f/tpadeny
	description: Teleport kérelmek letíltása
	trigger:

		if {-tpa::%uuid of player%::disabled} is not set:
			set {-tpa::%uuid of player%::disabled} to true
			send feedback("success", "&fLetíltottad a teleport kérelmeket!")

		else:
			delete {-tpa::%uuid of player%::disabled}
			send feedback("success", "&fMost már újra lehet teleport kérelmet küldeni neked!")