command /clearchat [<text>]:

	prefix: kockacraft
	aliases: cc
	executable by: console and players
	usage: &f/clearchat
	description: Chat kitörlése
	permission: clearchat
	trigger:

		switch arg-1:
			case "global":
				# wow
				loop 100 times:
					send_global_message("", "broadcast")

			case "local":
				loop 100 times:
					broadcast ""

on tab complete of "/clearchat" or "/cc":
	set tab completions for position 1 to "global", "local"