function create_bound(ID: text):

	set {_middle} to get_island_middle({_ID})

	set {_size} to get_island_size({_ID})
	set {_size_reversed} to ({_size} * -1)

	set {_location::1} to ({_middle} ~ (vector {_size}, 0, {_size}))
	set {_location::2} to ({_middle} ~ (vector {_size_reversed}, 0, {_size_reversed}))

	create temporary full bound with id {_ID} between {_location::1} and {_location::2}

	debug("&7Created bound for &8%format_short_uuid({_ID})%", script)