function anti_spam(p: player, limit: timespan) :: boolean:

	if {_p} has permission {config::server::permission::chat_bypass}:
		stop

	set {_time} to {-chat::%uuid of {_p}%::cooldown}
	set {_difference} to difference between {_time} and now

	set {-chat::%uuid of {_p}%::cooldown} to now

	if {_limit} > {_difference}:
		return true

	return false

on quit:
	delete {-chat::%uuid of {_p}%::cooldown}