custom event "remove money":
	pattern: remove money
	event-values: offlineplayer

function remove_money(p: offlineplayer, amount: number):

	set {_collection} to get_collection("economy")
	set {_document} to get_document("economy", "uuid", get_uuid({_p}))

	set {_balance} to mongo value "balance" of {_document}
	remove {_amount} from {_balance}

	set mongo value "balance" of {_document} to {_balance}
	update mongo document {_document} of {_collection}

	call custom event "remove money"