options:
	island-not-loaded: "&cEz a sziget nincs betöltve!"

#
# Játékos teleportálása egy szigetre
#
#    Args:
#        p (Player): Teleportálandó játékos
#        ID (integer): A sziget azonosítója
#
function teleport_player(p: player, ID: text):

	if is_island_loaded({_ID}) = false:
		send feedback("error", {@island-not-loaded}) to {_p}
		stop

	set {_location} to get_island_middle({_ID})
	teleport {_p} to {_location}